-- Explicitly revoke anon execution; PUBLIC alone does not remove explicit anon grants.
REVOKE EXECUTE ON FUNCTION public.ai_get_settings() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.ai_set_enabled(p_enabled boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.ai_upsert_provider(p_provider text, p_enabled boolean, p_priority integer, p_api_key text, p_account_id text, p_key_changed boolean, p_account_id_changed boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.approve_subscription_payment(p_payment_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.assign_initial_subscription() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.auto_cancel_overdue_policies() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.can_delete_customer(p_customer_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.can_delete_policy(p_policy_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.cancel_payment() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.cancel_severely_overdue_policies() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.check_in_own_appointment(p_appointment_id uuid, p_latitude double precision, p_longitude double precision) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.check_is_admin() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_webauthn_challenges() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.create_due_notifications() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.create_month_closing_reminders() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.delete_policy_safe(p_policy_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.find_ancestor_by_role_branch_aware(p_start_id uuid, p_branch_id uuid, p_target_role public.user_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.generate_installments(p_policy_id uuid, p_start_date date, p_payment_method public.payment_method, p_premium_amount numeric) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_collection_report(p_start_date date, p_end_date date, p_user_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_stats(p_user_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_my_manager_name() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_my_manager_name_branch_aware(p_branch_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_my_subscription_lock_state() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_org_node_production(p_user_ids uuid[], p_month_start date) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_org_node_production_branch_aware(p_user_ids uuid[], p_month_start date, p_branch_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_payable_subordinates(p_payer_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_target_progress(p_user_id uuid, p_month date) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_user_ancestors(p_user_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_user_subtree(user_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_user_subtree_branch_aware(user_id uuid, branch_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.handle_new_auth_user() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.import_policy_row(p_customer_name text, p_national_id text, p_phone text, p_address text, p_birth_date date, p_occupation text, p_marital_status text, p_agent_name text, p_policy_number text, p_policy_type text, p_sum_assured numeric, p_premium_amount numeric, p_payment_method text, p_start_date date, p_notes text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_month_closed(check_month date) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_super_admin() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.log_activity(p_action public.action_type, p_entity_type text, p_entity_id uuid, p_old_values jsonb, p_new_values jsonb) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.log_subscription_action(p_action text, p_target_user_id uuid, p_payment_id uuid, p_notes text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.mark_historical_installments_paid(p_policy_id uuid, p_paid_by_user_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.notify_from_activity_log() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.notify_users(p_user_ids uuid[], p_type public.notification_type, p_title text, p_message text, p_entity_type text, p_entity_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.prevent_self_privilege_escalation() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.reactivate_policy(p_policy_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.record_payment() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.regenerate_installments() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.reject_subscription_payment(p_payment_id uuid, p_reason text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.suspend_policy(p_policy_id uuid, p_reason text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.sync_primary_branch_role() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.transfer_user(p_user_id uuid, p_new_manager_id uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.update_overdue_installments() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.validate_user_branch_role_manager() FROM anon, public;

-- Required by the existing phone-login flow before authentication.
GRANT EXECUTE ON FUNCTION public.get_email_by_phone(p_phone text) TO anon;
